application: scotch-media
version: code
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1m"

builtins:
- appstats: off
- remote_api: off
- deferred: off

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /engineauth/docs/
  static_dir: engineauth

- url: /.*
  script: main.application


